// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo20tdrYbzHS7gVkxvzt8nUkRMp-xXUng',
    appId: '1:1086278312971:android:14ec22d549ee18e2e4d30e',
    messagingSenderId: '1086278312971',
    projectId: 'compare-your-exes',
    storageBucket: 'compare-your-exes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbyhPwiis1u2PuOyzoDLhlBxysyzZNIU',
    appId: '1:1086278312971:ios:6132efcc3829072de4d30e',
    messagingSenderId: '1086278312971',
    projectId: 'compare-your-exes',
    storageBucket: 'compare-your-exes.appspot.com',
    androidClientId: '1086278312971-m2uica37id301mcvf33ro2raonjhrjps.apps.googleusercontent.com',
    iosClientId: '1086278312971-nm4vuab9k7rvl1iue6917rhirvkl0vrp.apps.googleusercontent.com',
    iosBundleId: 'com.comp.ex',
  );
}
